version: '3'
services:
  forum_api_db:
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: forum_api_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=forum_api_db
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql-volume-forum:/var/lib/mysql

volumes:
  mysql-volume-forum: