CREATE TABLE role(
    id BIGINT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    PRIMARY KEY(id)
);

INSERT INTO role VALUES(1, 'LEITURA_ESCRITA');
INSERT INTO role VALUES(2, 'SOMENTE_LEITURA');